Todd-initial add of BIOS update

diff --git a/ztp/ztp/templates/ztp.j2 b/ztp/ztp/templates/ztp.j2
--- a/ztp/ztp/templates/ztp.j2
+++ b/ztp/ztp/templates/ztp.j2
@@ -39,6 +39,7 @@ HOSTNAME=$(echo "show system information | display xml" | cli | grep host-name |
 MGMT_INTF=$(cli -c "show dhcp client binding | no-more" | grep -i "bound" | grep -Eo -m 1 "(vme|em0|me0|fxp0)\.[0-9]+")
 MGMT_MAC=$(cli -c "show dhcp client binding | no-more" | grep -i "bound" | grep -E -m 1 "(vme|em0|me0|fxp0)\.[0-9]+"| awk -F" " '{print $2}')
 VERSION=$(echo "show system information | display xml" | cli | grep os-version | awk -F">" '{print $2}' | awk -F"<" '{print $1}')
+FW_VER=$(cli -c 'show chassis firmware|grep BIOS' | awk '{print $2}')
 
 if [ -z $SERIAL ]; then
     logger -t ztp "Could not retrieve device serial number"
@@ -64,12 +65,17 @@ if [ -z $VERSION ]; then
     exit 1
 fi
 
+if [ -z $FW_VER ]; then
+    logger -t ztp "Could not retrieve device BIOS version"
+fi
+
 DATA=$(cat <<EOF
 {
   "serial":"$SERIAL",
   "mac":"$MGMT_MAC",
   "hostname":"$HOSTNAME",
-  "version":"$VERSION"
+  "version":"$VERSION",
+  "fw_version":"$FW_VER"
 }
 EOF
 )
@@ -113,6 +119,51 @@ elif [ $STATUS_CODE -eq 200 ]; then
     fi
     logger -t ztp "Successfully loaded software image $NEW_VERSION ..."
     logger -t ztp "Preparing to reboot to finish software upgrade"
+    logger -t ztp "ZTP will start again afterwards to obtain the device config"
+    cleanup
+    cli -c "request system reboot at now"
+    exit 1
+else
+    logger -t ztp "Failed to retrieve software"
+    cleanup
+    exit 1
+fi
+
+logger -t ztp "Checking to see if EX4400 BIOS upgrade is needed"
+
+STATUS_CODE=$(curl -D http_resp_raw -OJfsS -w "%{http_code}\n" -k -d "$DATA" -H 'Content-Type: application/json' https://{{ztp_server}}:{{ztp_port}}/firmware)
+if [ ! -f http_resp_raw ]; then
+    logger -t ztp "http_resp_raw not found"
+    cleanup
+    exit 1
+fi
+
+tr -d '\r' < http_resp_raw > http_resp || cp -f http_resp_raw http_resp
+
+if [ $STATUS_CODE -eq 204 ]; then
+    MSG=$(grep -i firmware-message http_resp | awk -F ': ' '{print $2}')
+    logger -t ztp "$MSG"
+elif [ $STATUS_CODE -eq 200 ]; then
+    FW_FILENAME=$(grep -i content-disposition http_resp | awk -F 'filename=' '{print $2}')
+    logger -t ztp "Starting firmware upgrade ..."
+    CLI_RESP=$(cli -c "request system software add $JUNOS_TMPDIR/$FW_FILENAME")
+    CLI_RESP_ERRS=$(echo $CLI_RESP | grep 'error')
+    if [ $? -eq 0 ]; then
+        echo $CLI_RESP
+        logger -t ztp "failed to add firmware upgrade package"
+        cleanup
+        exit 1
+    fi
+    CLI_RESP=$(cli -c "request system firmware upgrade jfirmware bios")
+    CLI_RESP_ERRS=$(echo $CLI_RESP | grep 'rror')
+    if [ $? -eq 0 ]; then
+        echo $CLI_RESP
+        logger -t ztp "failed to initiate firmware upgrade"
+        cleanup
+        exit 1
+    fi
+    logger -t ztp "Successfully loaded BIOS image ..."
+    logger -t ztp "Preparing to reboot to finish BIOS upgrade"
     logger -t ztp "ZTP will start again afterwards to obtain the device config"
     cleanup
     cli -c "request system reboot at now"
